export const PATH_SEGMENTS = {
  CLIENTE_MOTOS: 'motos',
  CLIENTE_AGENDAMENTOS: 'agendamentos',
  CLIENTE_REVISOES: 'revisoes',
  CLIENTE_CONCESSIONARIAS: 'concessionarias',
  
  CONCESSIONARIA_DASHBOARD: 'dashboard',
  CONCESSIONARIA_LOJAS: 'lojas',
  CONCESSIONARIA_AGENDAMENTOS: 'agendamentos',
  CONCESSIONARIA_CATALOGOS: 'catalogos',
  CONCESSIONARIA_CATALOGOS_MOTOS: 'catalogos-motos',
  CONCESSIONARIA_CATALOGOS_REVISOES: 'catalogos-revisoes',
  CONCESSIONARIA_CATALOGOS_PECAS: 'catalogos-pecas',
  CONCESSIONARIA_CATALOGOS_PECAS_CREATE: 'catalogos-pecas/novo',
  CONCESSIONARIA_CATALOGOS_SERVICOS: 'catalogos-servicos',
};

export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  CADASTRO: '/cadastro',
  ACCESS_DENIED: '/access-denied',
  DASHBOARD_CLIENTE: '/dashboard/cliente',
  DASHBOARD_CONCESSIONARIA: '/dashboard/concessionaria',
  
  ESQUECI_SENHA: '/esqueci-senha',
  PERFIL_USUARIO: '/perfil',

  CLIENTE_MOTOS: `/dashboard/cliente/${PATH_SEGMENTS.CLIENTE_MOTOS}`,
  CLIENTE_AGENDAMENTOS: `/dashboard/cliente/${PATH_SEGMENTS.CLIENTE_AGENDAMENTOS}`,
  CLIENTE_REVISOES: `/dashboard/cliente/${PATH_SEGMENTS.CLIENTE_REVISOES}`,
  CLIENTE_CONCESSIONARIAS: `/dashboard/cliente/${PATH_SEGMENTS.CLIENTE_CONCESSIONARIAS}`,

  CONCESSIONARIA_DASHBOARD: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_DASHBOARD}`,
  CONCESSIONARIA_LOJAS: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_LOJAS}`,
  CONCESSIONARIA_AGENDAMENTOS: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_AGENDAMENTOS}`,
  CONCESSIONARIA_CATALOGOS: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_CATALOGOS}`,
  CONCESSIONARIA_CATALOGOS_MOTOS: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_CATALOGOS_MOTOS}`,
  CONCESSIONARIA_CATALOGOS_REVISOES: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_CATALOGOS_REVISOES}`,
  CONCESSIONARIA_CATALOGOS_PECAS: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_CATALOGOS_PECAS}`,
  CONCESSIONARIA_CATALOGOS_PECAS_CREATE: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_CATALOGOS_PECAS_CREATE}`,
  CONCESSIONARIA_CATALOGOS_SERVICOS: `/dashboard/concessionaria/${PATH_SEGMENTS.CONCESSIONARIA_CATALOGOS_SERVICOS}`,
};
